# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/00_core.ipynb (unless otherwise specified).

__all__ = ['read_metadata']

# Cell
from fastai.imports import *

# Cell
def read_metadata(fn):
    "read DFDC competition metadata as pd.DataFrame"
    metadf = pd.read_json(fn).T.reset_index()
    metadf.columns = ['fname','label','split','original']
    return metadf