# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/02_download_unzip_files.ipynb (unless otherwise specified).

__all__ = ['download_parts', 'download_unzip']

# Cell
from fastai.imports import *
download_parts = ["0"+i if len(i) == 1 else i for i in map(str, range(50))]

# Cell
def download_unzip(part_no="01"):
    "download, unzip and remove zip part file return unzipped dir path"
    data_path = Path("/home/ubuntu/data/dfdc/")
    data_video_path = data_path/'dfdc_train'
    cookies_path = data_path/'cookies.txt'

    url = f"https://www.kaggle.com/c/16880/datadownload/dfdc_train_part_{part_no}.zip"
    output = data_path/f'dfdc_train/dfdc_train_part_{part_no}.zip'
    cmd = f"wget --load-cookies {cookies_path} {url} -O {output}"
    os.system(cmd)

    shutil.unpack_archive(str(output), str(output.parent))
    os.remove(output)
    splits = output.stem.split('_')
    dirname = "_".join(splits[:-1] + [splits[-1][1:] if splits[-1].startswith('0') else splits[-1]])
    return output.parent/dirname